name = "xaip-trust-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

[vars]
XAIP_VERSION = "0.4.0"
AGGREGATOR_NODES = "https://xaip-aggregator.kuma-github.workers.dev"

[[services]]
binding = "AGGREGATOR_SERVICE"
service = "xaip-aggregator"
